const SIGN_UP_WHIT_EMAIL_AND_PASSWORD = "SIGN_UP_WHIT_EMAIL_AND_PASSWORD";
const LOG_IN_WHIT_EMAIL = "LOG_IN_WHIT_EMAIL";
const LOG_OUT = "LOG_OUT";
const LOG_IN_WITH_GOOGLE = "LOG_IN_WITH_GOOGLE";
const LOG_IN_WITH_FACEBOOK = "LOG_IN_WITH_FACEBOOK";
const GET_FIELDS = "GET_FIELDS";
const GET_MATCHES = "GET_MATCHES";
const JOIN_MATCH = "JOIN_MATCH";
const GET_DETAILS_USER = "GET_DETAILS_USER";
const GET_USERS = "GET_USERS";
const GET_DETAILS_COURT = "GET_DETAILS_COURT";
const GET_DETAILS_MATCH = "GET_DETAILS_MATCH";
const GET_NEIGHBORHOODS = "GET_NEIGHBORHOODS";
const REMOVE_PLAYER = "REMOVE_PLAYER";

export {
  SIGN_UP_WHIT_EMAIL_AND_PASSWORD,
  LOG_IN_WHIT_EMAIL,
  LOG_OUT,
  LOG_IN_WITH_GOOGLE,
  LOG_IN_WITH_FACEBOOK,
  GET_FIELDS,
  GET_MATCHES,
  JOIN_MATCH,
  GET_DETAILS_USER,
  GET_USERS,
  GET_DETAILS_COURT,
  GET_DETAILS_MATCH,
  GET_NEIGHBORHOODS,
  REMOVE_PLAYER,
};
