const SIGN_UP_WHIT_EMAIL_AND_PASSWORD = "SIGN_UP_WHIT_EMAIL_AND_PASSWORD";
const LOG_IN_WHIT_EMAIL = "LOG_IN_WHIT_EMAIL";
const LOG_OUT = "LOG_OUT";
const LOG_IN_WITH_GOOGLE = "LOG_IN_WITH_GOOGLE";
const LOG_IN_WITH_FACEBOOK = "LOG_IN_WITH_FACEBOOK";
const GET_FIELDS = "GET_FIELDS";
const GET_MATCHES = "GET_MATCHES";
const JOIN_MATCH = "JOIN_MATCH";
const GET_DETAILS_USER = "GET_DETAILS_USER";
const GET_USERS = "GET_USERS";
const GET_DETAILS_COURT = "GET_DETAILS_COURT";
const GET_DETAILS_MATCH = "GET_DETAILS_MATCH";
const GET_NEIGHBORHOODS = "GET_NEIGHBORHOODS";
const USER_BY_NAME = "USER_BY_NAME";
const FILTER_BY_POSITION = "FILTER_BY_POSITION";
const FILTER_BY_NEIGHBORHOOD = "FILTER_BY_NEIGHBORHOOD";
const REMOVE_PLAYER = "REMOVE_PLAYER";
const ORDER_BY_PLAYERS = "ORDER_BY_PLAYERS";
const ORDER_BY_DATE = "ORDER_BY_DATE";
const UPDATE_DATA_USER = "UPDATE_DATA_USER";
const RESET_PLAYERS_FILTER = "RESET_PLAYERS_FILTER";
const MATCH_BY_NAME_SPORTCENTER = "MATCH_BY_NAME_SPORTCENTER";
const FILTER_SPORTCENTER = "FILTER_SPORTCENTER";
const SHOW_YOUR_MATCHES = "SHOW_YOUR_MATCHES"

export {
  SIGN_UP_WHIT_EMAIL_AND_PASSWORD,
  LOG_IN_WHIT_EMAIL,
  LOG_OUT,
  LOG_IN_WITH_GOOGLE,
  LOG_IN_WITH_FACEBOOK,
  GET_FIELDS,
  GET_MATCHES,
  JOIN_MATCH,
  GET_DETAILS_USER,
  GET_USERS,
  GET_DETAILS_COURT,
  GET_DETAILS_MATCH,
  GET_NEIGHBORHOODS,
  USER_BY_NAME,
  FILTER_BY_POSITION,
  FILTER_BY_NEIGHBORHOOD,
  REMOVE_PLAYER,
  ORDER_BY_PLAYERS,
  ORDER_BY_DATE,
  UPDATE_DATA_USER,
  RESET_PLAYERS_FILTER,
  MATCH_BY_NAME_SPORTCENTER,
  FILTER_SPORTCENTER,
  SHOW_YOUR_MATCHES
};
